# Generated by Django 3.2.7 on 2021-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitudApp', '0002_solicitar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitar',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
