# Generated by Django 3.2.7 on 2021-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='ciudad')),
                ('punto1', models.CharField(max_length=50)),
                ('punto2', models.CharField(blank=True, max_length=50, null=True)),
                ('punto3', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lugartop',
                'verbose_name_plural': 'lugarestops',
            },
        ),
        migrations.CreateModel(
            name='Recomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='ciudad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'recomendado',
                'verbose_name_plural': 'recomendados',
            },
        ),
    ]
