# Generated by Django 3.2.7 on 2021-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CiudadApp', '0002_lugartop_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugartop',
            name='descripcion',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='lugartop',
            name='punto1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lugartop',
            name='punto2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lugartop',
            name='punto3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
