# Generated by Django 3.2.7 on 2021-10-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CiudadApp', '0005_requisito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requisito',
        ),
    ]
