# Generated by Django 3.2.7 on 2021-10-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotosnoticia',
            old_name='noticia',
            new_name='nombre',
        ),
    ]
