# Generated by Django 3.2.7 on 2021-10-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0015_auto_20211020_2111'),
        ('NoticiasApp', '0002_rename_noticia_fotosnoticia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='oficina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InicioApp.oficina'),
            preserve_default=False,
        ),
    ]
