# Generated by Django 3.2.7 on 2021-10-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasApp', '0003_alter_noticia_oficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotosnoticia',
            name='oficina',
        ),
    ]
