# Generated by Django 3.2.9 on 2022-02-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspacioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
