# Generated by Django 3.2.9 on 2022-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspacioApp', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bandera',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
