# Generated by Django 3.2.7 on 2021-10-17 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InicioApp', '0003_categorianoticia_fotosnoticia_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannersPaginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pagina', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
