# Generated by Django 3.2.7 on 2021-10-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0004_bannerspaginas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerspaginas',
            options={'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
    ]
