# Generated by Django 3.2.7 on 2021-10-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0005_alter_bannerspaginas_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannersPaginas',
        ),
    ]
