# Generated by Django 3.2.7 on 2021-10-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0007_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='imagen',
            field=models.ImageField(default='', upload_to='archivos_requisitos/img'),
            preserve_default=False,
        ),
    ]
