# Generated by Django 3.2.7 on 2021-10-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0008_requisito_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotosnoticia',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='fotosnoticia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CategoriaNoticia',
        ),
        migrations.DeleteModel(
            name='FotosNoticia',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
