# Generated by Django 3.2.7 on 2021-10-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0011_auto_20211020_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='requisito',
            name='oficina',
        ),
    ]
