# Generated by Django 3.2.7 on 2021-10-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioApp', '0012_auto_20211020_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oficina',
        ),
    ]
